language: go
go:
  - tip
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - go get github.com/aryann/difflib
  - go get ./...
script:
  - ./test.sh
env:
  global:
    - PQT_POSTGRES_ADDRESS=postgres://postgres:@localhost/travis_ci_test?sslmode=disable
after_success:
  - bash <(curl -s https://codecov.io/bash)