dist: trusty
language: go
go:
  - 1.9.x
addons:
  postgresql: '9.5'
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
before_install:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mkdir -p $GOPATH/bin
install:
  - go get github.com/aryann/difflib
  - go get .
  - go get ./pqtgo
  - go get ./pqtsql
  - cd ./example/ && glide install
  - cd ../
script:
  - ./test.sh
env:
  global:
    - PQT_POSTGRES_ADDRESS=postgres://postgres:@localhost/travis_ci_test?sslmode=disable
after_success:
  - bash <(curl -s https://codecov.io/bash)